// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proxy/tendermint/tendermint.proto

package tendermint

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	tendermint "github.com/hyperledger-labs/yui-relayer/chains/tendermint"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProxyChainConfig struct {
	ChainConfig *tendermint.ChainConfig `protobuf:"bytes,1,opt,name=chain_config,json=chainConfig,proto3" json:"chain_config,omitempty"`
}

func (m *ProxyChainConfig) Reset()         { *m = ProxyChainConfig{} }
func (m *ProxyChainConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyChainConfig) ProtoMessage()    {}
func (*ProxyChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dbd11c4cb043c13, []int{0}
}
func (m *ProxyChainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProxyChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProxyChainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProxyChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyChainConfig.Merge(m, src)
}
func (m *ProxyChainConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProxyChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyChainConfig proto.InternalMessageInfo

func (m *ProxyChainConfig) GetChainConfig() *tendermint.ChainConfig {
	if m != nil {
		return m.ChainConfig
	}
	return nil
}

type ProxyChainProverConfig struct {
	ProverConfig *tendermint.ProverConfig `protobuf:"bytes,1,opt,name=prover_config,json=proverConfig,proto3" json:"prover_config,omitempty"`
}

func (m *ProxyChainProverConfig) Reset()         { *m = ProxyChainProverConfig{} }
func (m *ProxyChainProverConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyChainProverConfig) ProtoMessage()    {}
func (*ProxyChainProverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dbd11c4cb043c13, []int{1}
}
func (m *ProxyChainProverConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProxyChainProverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProxyChainProverConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProxyChainProverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyChainProverConfig.Merge(m, src)
}
func (m *ProxyChainProverConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProxyChainProverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyChainProverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyChainProverConfig proto.InternalMessageInfo

func (m *ProxyChainProverConfig) GetProverConfig() *tendermint.ProverConfig {
	if m != nil {
		return m.ProverConfig
	}
	return nil
}

func init() {
	proto.RegisterType((*ProxyChainConfig)(nil), "ibc.proxy.tendermint.v1.ProxyChainConfig")
	proto.RegisterType((*ProxyChainProverConfig)(nil), "ibc.proxy.tendermint.v1.ProxyChainProverConfig")
}

func init() { proto.RegisterFile("proxy/tendermint/tendermint.proto", fileDescriptor_9dbd11c4cb043c13) }

var fileDescriptor_9dbd11c4cb043c13 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x9b, 0x85, 0xc1, 0x2d, 0x12, 0xaa, 0x10, 0x3f, 0x1d, 0x2c, 0xe8, 0x80, 0x58, 0x62,
	0x0b, 0x98, 0x59, 0xe8, 0x0b, 0x44, 0x65, 0x40, 0x62, 0x41, 0xb6, 0xe3, 0xba, 0x16, 0x89, 0xaf,
	0x65, 0xdc, 0x8a, 0xbc, 0x05, 0x8f, 0xc5, 0xd8, 0x91, 0x11, 0x25, 0x2f, 0x82, 0x62, 0x47, 0xaa,
	0x61, 0x61, 0xbb, 0x47, 0xf7, 0xe4, 0xfb, 0xa2, 0x6b, 0x74, 0x69, 0x1d, 0xbc, 0x37, 0xd4, 0x4b,
	0x53, 0x4a, 0x57, 0x6b, 0xe3, 0x93, 0x91, 0x58, 0x07, 0x1e, 0xa6, 0xa7, 0x9a, 0x0b, 0x12, 0x6a,
	0x24, 0xd9, 0x6d, 0x6f, 0x66, 0xc7, 0x0a, 0x14, 0x84, 0x0e, 0xed, 0xa7, 0x58, 0x9f, 0x9d, 0x2b,
	0x00, 0x55, 0x49, 0x1a, 0x12, 0xdf, 0xac, 0x28, 0x33, 0xcd, 0xb0, 0xba, 0x72, 0xb2, 0x62, 0x8d,
	0x74, 0x54, 0xac, 0x99, 0x36, 0x6f, 0xa9, 0x55, 0x80, 0x59, 0x69, 0x15, 0x7b, 0xf3, 0x12, 0x1d,
	0x15, 0xbd, 0x6f, 0xd1, 0xd7, 0x16, 0x61, 0x33, 0x2d, 0xd0, 0x24, 0x7c, 0xf5, 0x12, 0x9b, 0x67,
	0xd9, 0x45, 0x76, 0x3d, 0xbe, 0xcd, 0xc9, 0x80, 0x24, 0x11, 0x99, 0xfe, 0xe1, 0x80, 0x4c, 0x20,
	0xcb, 0xb1, 0xd8, 0x87, 0x79, 0x8d, 0x4e, 0xf6, 0x96, 0xc2, 0xc1, 0x56, 0xba, 0xc1, 0xf5, 0x88,
	0x0e, 0x6d, 0xc8, 0xbf, 0x65, 0xe4, 0x7f, 0x59, 0x8a, 0x59, 0x4e, 0x6c, 0x92, 0x1e, 0x9e, 0x3e,
	0x5b, 0x9c, 0xed, 0x5a, 0x9c, 0x7d, 0xb7, 0x38, 0xfb, 0xe8, 0xf0, 0x68, 0xd7, 0xe1, 0xd1, 0x57,
	0x87, 0x47, 0xcf, 0xf7, 0x4a, 0xfb, 0xf5, 0x86, 0x13, 0x01, 0x35, 0x2d, 0x99, 0x67, 0x81, 0x5e,
	0x31, 0x4e, 0x35, 0x17, 0x79, 0x38, 0x7c, 0x1e, 0x49, 0xd4, 0xbe, 0x2a, 0xfa, 0xf7, 0xc1, 0xf8,
	0x41, 0x38, 0xda, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x6f, 0x81, 0xd5, 0xcb, 0x01,
	0x00, 0x00,
}

func (m *ProxyChainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProxyChainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProxyChainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChainConfig != nil {
		{
			size, err := m.ChainConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTendermint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProxyChainProverConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProxyChainProverConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProxyChainProverConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProverConfig != nil {
		{
			size, err := m.ProverConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTendermint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTendermint(dAtA []byte, offset int, v uint64) int {
	offset -= sovTendermint(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProxyChainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainConfig != nil {
		l = m.ChainConfig.Size()
		n += 1 + l + sovTendermint(uint64(l))
	}
	return n
}

func (m *ProxyChainProverConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProverConfig != nil {
		l = m.ProverConfig.Size()
		n += 1 + l + sovTendermint(uint64(l))
	}
	return n
}

func sovTendermint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTendermint(x uint64) (n int) {
	return sovTendermint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProxyChainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTendermint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProxyChainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProxyChainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTendermint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTendermint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTendermint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChainConfig == nil {
				m.ChainConfig = &tendermint.ChainConfig{}
			}
			if err := m.ChainConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTendermint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTendermint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProxyChainProverConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTendermint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProxyChainProverConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProxyChainProverConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProverConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTendermint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTendermint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTendermint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProverConfig == nil {
				m.ProverConfig = &tendermint.ProverConfig{}
			}
			if err := m.ProverConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTendermint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTendermint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTendermint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTendermint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTendermint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTendermint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTendermint
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTendermint
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTendermint
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTendermint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTendermint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTendermint = fmt.Errorf("proto: unexpected end of group")
)
